<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CalonSiswaSeeder extends Seeder
{
    /**
     * Seed 39 data calon siswa beserta data pendaftaran mereka.
     * Data ini adalah data riil calon siswa SPMB MI Nurussalam.
     */
    public function run(): void
    {
        // Nonaktifkan foreign key checks sementara untuk menjamin urutan insert aman
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        // ---------------------------------------------------------------
        // DATA USERS (39 akun calon siswa)
        // ---------------------------------------------------------------
        $users = [
            [
                'id'                => 2,
                'username'          => 'Atha Rayhaan Shakeil',
                'email'             => 'wadi07578@gmail.com',
                'password'          => '$2y$12$bt/YUeBSwiDuQFwmkLKvG.XKvbmKW7IO4uiBKBybdEvrbj5sgDRui',
                'role'              => 'siswa',
                'email_verified_at' => '2026-08-22 14:18:46',
                'created_at'        => '2026-08-22 14:18:00',
                'updated_at'        => '2026-08-22 14:18:46',
            ],
            [
                'id'                => 3,
                'username'          => 'Azzahra Salsabila',
                'email'             => 'azzahrasalsabila@gmail.com',
                'password'          => '$2y$12$bcNaJpsIdWB69Ygu7G9qIO5R2v/47i9t20yXdMLCg21iYWmi9tqnK',
                'role'              => 'siswa',
                'email_verified_at' => '2026-08-22 15:41:00',
                'created_at'        => '2026-08-22 15:41:00',
                'updated_at'        => '2026-08-22 15:41:00',
            ],
            [
                'id'                => 4,
                'username'          => 'Keysha Al-Khanza',
                'email'             => 'keyshaalkhanza@gmail.com',
                'password'          => '$2y$12$an8JaMkM4Ayn6ouD7Zvqf.BUe9U9FSyPXshFOcl5M4oMCqeogzRWC',
                'role'              => 'siswa',
                'email_verified_at' => '2026-08-22 15:41:01',
                'created_at'        => '2026-08-22 15:41:01',
                'updated_at'        => '2026-08-22 15:41:01',
            ],
            [
                'id'                => 5,
                'username'          => 'Nadhira Rahma Falisha',
                'email'             => 'nadhirarahmafalisha@gmail.com',
                'password'          => '$2y$12$ErEdfzQW7zis0ggnuUzQcOzXD2RN8lVI6.tzyLhzjdunJjxQRCSf.',
                'role'              => 'siswa',
                'email_verified_at' => '2026-08-22 15:41:01',
                'created_at'        => '2026-08-22 15:41:01',
                'updated_at'        => '2026-08-22 15:41:01',
            ],
            [
                'id'                => 6,
                'username'          => 'Zaidan Syafiq Ardiaz',
                'email'             => 'zaidansyafiqardiaz@gmail.com',
                'password'          => '$2y$12$EKpKK288TwFzbzAyqFRqt.JJbPMUunPI8Bt483THS1a.QzLMUHQeS',
                'role'              => 'siswa',
                'email_verified_at' => '2026-08-22 15:41:02',
                'created_at'        => '2026-08-22 15:41:02',
                'updated_at'        => '2026-08-22 15:41:02',
            ],
            [
                'id'                => 7,
                'username'          => 'Arsya Maulana Romadhan',
                'email'             => 'arsyamaulanaromadhan@gmail.com',
                'password'          => '$2y$12$epq5yStb1xe33ajMT4iB1O8UKStXukls4Unv.82Wxk9OrL9EgOH1G',
                'role'              => 'siswa',
                'email_verified_at' => '2026-08-22 15:41:02',
                'created_at'        => '2026-08-22 15:41:02',
                'updated_at'        => '2026-08-22 15:41:02',
            ],
            [
                'id'                => 8,
                'username'          => 'Salsa Kirana Zahrani',
                'email'             => 'salsakiranazahrani@gmail.com',
                'password'          => '$2y$12$VSmShYX/eevM3DouJctxk.cPX/yZhV063eOjgeJ04q.5j5k5d54tm',
                'role'              => 'siswa',
                'email_verified_at' => '2026-08-22 16:09:16',
                'created_at'        => '2026-08-22 16:09:16',
                'updated_at'        => '2026-08-22 16:09:16',
            ],
            [
                'id'                => 9,
                'username'          => 'Husna Ayunindya',
                'email'             => 'husnaayunindya@gmail.com',
                'password'          => '$2y$12$3mDsaqY5htp90.2e6nMeluUX3agDfW7/Jy.gwr60uzZonNB9ZfdEq',
                'role'              => 'siswa',
                'email_verified_at' => '2026-08-22 16:09:16',
                'created_at'        => '2026-08-22 16:09:16',
                'updated_at'        => '2026-08-22 16:09:16',
            ],
            [
                'id'                => 10,
                'username'          => 'Karel Al Sadad',
                'email'             => 'karelalsadad@gmail.com',
                'password'          => '$2y$12$OX8RJxdSWKkKswnAJ66LNOeM6Li62H29lcLJsMmSYvFUpZ5M2seCO',
                'role'              => 'siswa',
                'email_verified_at' => '2026-08-22 16:09:17',
                'created_at'        => '2026-08-22 16:09:17',
                'updated_at'        => '2026-08-22 16:09:17',
            ],
            [
                'id'                => 11,
                'username'          => 'Afifa Titiya',
                'email'             => 'afifatitiya@gmail.com',
                'password'          => '$2y$12$geWQShb1tvKabpdDG84W1enw7mxEnry4GMFlnOHwdj2tEEDBFBx5y',
                'role'              => 'siswa',
                'email_verified_at' => '2026-08-22 16:09:17',
                'created_at'        => '2026-08-22 16:09:17',
                'updated_at'        => '2026-08-22 16:09:17',
            ],
            [
                'id'                => 12,
                'username'          => 'M. Syailendra Dirga Vernando',
                'email'             => 'syailendradirga@gmail.com',
                'password'          => '$2y$12$ZLZ2/vYJuJO6//dyZPTW5uBx23doj6IYjzGmy5np3nQERirlC2xKC',
                'role'              => 'siswa',
                'email_verified_at' => '2026-08-22 16:09:18',
                'created_at'        => '2026-08-22 16:09:18',
                'updated_at'        => '2026-08-22 16:09:18',
            ],
            [
                'id'                => 13,
                'username'          => 'Angga Wijaya',
                'email'             => 'anggawijaya@gmail.com',
                'password'          => '$2y$12$UDc.e6sw9t43QX2hDxk9DOd5qMH2BUGdtFKhOPCL7FuqSHTJNavpa',
                'role'              => 'siswa',
                'email_verified_at' => '2026-08-22 16:09:18',
                'created_at'        => '2026-08-22 16:09:18',
                'updated_at'        => '2026-08-22 16:09:18',
            ],
            [
                'id'                => 14,
                'username'          => 'Aisyah',
                'email'             => 'aisyah.spmb26@gmail.com',
                'password'          => '$2y$12$NkLyOCfZPhdck41cC.Hk9.f57L1uQVV1GFGNneGq5LpwaHdDv.7Ea',
                'role'              => 'siswa',
                'email_verified_at' => '2026-08-22 16:09:18',
                'created_at'        => '2026-08-22 16:09:18',
                'updated_at'        => '2026-08-22 16:09:18',
            ],
            [
                'id'                => 15,
                'username'          => 'Alifa Azzalia',
                'email'             => 'alifaazzalia@gmail.com',
                'password'          => '$2y$12$ZGoBmyuocEdw3WMT1W3gwOYBQ8ocs2.n4hu2kGCNPvtUVw05w9HtO',
                'role'              => 'siswa',
                'email_verified_at' => '2026-08-22 16:09:18',
                'created_at'        => '2026-08-22 16:09:18',
                'updated_at'        => '2026-08-22 16:09:18',
            ],
            [
                'id'                => 16,
                'username'          => 'Bilal Al Rasyid',
                'email'             => 'bilalalrasyid@gmail.com',
                'password'          => '$2y$12$O2RTmknSKbvdtg38FH0iXuWb3aJToyVH05NjoDrLbpW4PD6WvyLEe',
                'role'              => 'siswa',
                'email_verified_at' => '2026-08-22 16:09:19',
                'created_at'        => '2026-08-22 16:09:19',
                'updated_at'        => '2026-08-22 16:09:19',
            ],
            [
                'id'                => 17,
                'username'          => 'Asyifa Umi Sabrina',
                'email'             => 'asyifaumisabrina@gmail.com',
                'password'          => '$2y$12$.mnuY7Zn85TuiaGuOWxyVux8JkO7wHgDB8HLEgMNGHGWtjbJTuCP2',
                'role'              => 'siswa',
                'email_verified_at' => '2026-08-22 16:09:19',
                'created_at'        => '2026-08-22 16:09:19',
                'updated_at'        => '2026-08-22 16:09:19',
            ],
            [
                'id'                => 18,
                'username'          => 'Azwan Rafasya',
                'email'             => 'azwanrafasya@gmail.com',
                'password'          => '$2y$12$5MLDG8c7C.eAR5NZOfIlmeOA5Zx2dPpxh/B6UOp11WHHOVmYjHnum',
                'role'              => 'siswa',
                'email_verified_at' => '2026-08-22 16:09:19',
                'created_at'        => '2026-08-22 16:09:19',
                'updated_at'        => '2026-08-22 16:09:19',
            ],
            [
                'id'                => 19,
                'username'          => 'Alfania Layla Syakira Ramadhani',
                'email'             => 'alfanialaylasyakira@gmail.com',
                'password'          => '$2y$12$Q4tWZ4PftUX6.PsZT9hOv.I4C3oUTBLnqR2YqB6l.T8MpP7Y8ssd.',
                'role'              => 'siswa',
                'email_verified_at' => '2026-08-22 16:09:20',
                'created_at'        => '2026-08-22 16:09:20',
                'updated_at'        => '2026-08-22 16:09:20',
            ],
            [
                'id'                => 20,
                'username'          => 'Rizki Maulana Saputra',
                'email'             => 'rizkimaulanasaputra@gmail.com',
                'password'          => '$2y$12$j4Wwd4FLhxcgKnsoCR3DduVE3yKylMug9Zzc6czAZg7rkpI889Bbi',
                'role'              => 'siswa',
                'email_verified_at' => '2026-08-22 16:09:20',
                'created_at'        => '2026-08-22 16:09:20',
                'updated_at'        => '2026-08-22 16:09:20',
            ],
            [
                'id'                => 21,
                'username'          => 'Al Khaisyan Putra Pamungkas',
                'email'             => 'alkhaisyanputra@gmail.com',
                'password'          => '$2y$12$ek2VwhL4Xi0eafOH.8MiaOABoKst3Xy0oTkyu0vy8wPgfcT4eeQRO',
                'role'              => 'siswa',
                'email_verified_at' => '2026-08-22 16:09:20',
                'created_at'        => '2026-08-22 16:09:20',
                'updated_at'        => '2026-08-22 16:09:20',
            ],
            [
                'id'                => 22,
                'username'          => 'Kms. Muhammad Rofiq Al Maulidy',
                'email'             => 'muhammadrofiq20@gmail.com',
                'password'          => '$2y$12$Q6L993KivGXnEgf7MWf3auKJje0gNEhukH5Nfb4n9uvFHIixKswrm',
                'role'              => 'siswa',
                'email_verified_at' => '2026-08-22 16:09:20',
                'created_at'        => '2026-08-22 16:09:20',
                'updated_at'        => '2026-08-22 16:09:20',
            ],
            [
                'id'                => 23,
                'username'          => 'Nad Nazhif Fikri',
                'email'             => 'nadnazhiffikri@gmail.com',
                'password'          => '$2y$12$cjut4tp36QCRvj6h8nN9Yu/y2Thr2sMrHATHz8nhr/ZpBif27XNKa',
                'role'              => 'siswa',
                'email_verified_at' => '2026-08-22 16:09:21',
                'created_at'        => '2026-08-22 16:09:21',
                'updated_at'        => '2026-08-22 16:09:21',
            ],
            [
                'id'                => 24,
                'username'          => 'Erina Rayya Assyauqie',
                'email'             => 'erinarayyaassyauqie@gmail.com',
                'password'          => '$2y$12$bkmd5/82KY4jm17rtcMML.jS8cAb0sGBnF.DkZbpomcM3YlYtdW5y',
                'role'              => 'siswa',
                'email_verified_at' => '2026-08-22 16:09:21',
                'created_at'        => '2026-08-22 16:09:21',
                'updated_at'        => '2026-08-22 16:09:21',
            ],
            [
                'id'                => 25,
                'username'          => 'Hafiz Nur Rahman',
                'email'             => 'hafiznurrahman@gmail.com',
                'password'          => '$2y$12$wBAKyzM2yAegvWWdJbtWve8Taz5cWVr7.2Cq0X9NFHO8xEIsmpDh2',
                'role'              => 'siswa',
                'email_verified_at' => '2026-08-22 16:09:21',
                'created_at'        => '2026-08-22 16:09:21',
                'updated_at'        => '2026-08-22 16:09:21',
            ],
            [
                'id'                => 26,
                'username'          => 'Saffana Nasha Fawzia',
                'email'             => 'saffananashafawzia@gmail.com',
                'password'          => '$2y$12$3q62smvyZ6QO5cCnvIAA4eZNVQnW/VcvRDGkXHBTfzKaL7LXr9FIS',
                'role'              => 'siswa',
                'email_verified_at' => '2026-08-22 16:09:22',
                'created_at'        => '2026-08-22 16:09:22',
                'updated_at'        => '2026-08-22 16:09:22',
            ],
            [
                'id'                => 27,
                'username'          => 'Noval Devan At Taimifah',
                'email'             => 'novaldevanattaimifah@gmail.com',
                'password'          => '$2y$12$AemvchbgLT8YFXrY1ykHfOTayNlYXgm3C/j9GuuJ5HEKHcT80XT/6',
                'role'              => 'siswa',
                'email_verified_at' => '2026-08-22 16:09:22',
                'created_at'        => '2026-08-22 16:09:22',
                'updated_at'        => '2026-08-22 16:09:22',
            ],
            [
                'id'                => 28,
                'username'          => 'Alya Dinda Kamala',
                'email'             => 'alyadindakamala@gmail.com',
                'password'          => '$2y$12$8Yt5zvoXGtZbMAoFOBtqoeP.BmIHQW1yTeYXTprWO3BwIRBuYMP0K',
                'role'              => 'siswa',
                'email_verified_at' => '2026-08-22 16:09:22',
                'created_at'        => '2026-08-22 16:09:22',
                'updated_at'        => '2026-08-22 16:09:22',
            ],
            [
                'id'                => 29,
                'username'          => 'Muhaimin Ahmad',
                'email'             => 'muhaiminahmad@gmail.com',
                'password'          => '$2y$12$AUzPDRwnrale/.zA6yppf./aTZlUsNc/7yESTkxHFtVeBAjHLSbKS',
                'role'              => 'siswa',
                'email_verified_at' => '2026-08-22 16:09:22',
                'created_at'        => '2026-08-22 16:09:22',
                'updated_at'        => '2026-08-22 16:09:22',
            ],
            [
                'id'                => 30,
                'username'          => 'Narendra Rayyan Atha Razka',
                'email'             => 'narendrarayyan@gmail.com',
                'password'          => '$2y$12$ETOg.gYD7JypEY4dGVzAnOnj9OgcqE9Q3CBFiooTXjb5iFN7AnLhm',
                'role'              => 'siswa',
                'email_verified_at' => '2026-08-22 16:09:23',
                'created_at'        => '2026-08-22 16:09:23',
                'updated_at'        => '2026-08-22 16:09:23',
            ],
            [
                'id'                => 31,
                'username'          => 'Muhammad Haidar El Fayyadh',
                'email'             => 'haidarelfayyadh@gmail.com',
                'password'          => '$2y$12$kPfGoyroydhJN2K38EInKeq09DXekAMbfeudaa..WEhxRGRvylRzm',
                'role'              => 'siswa',
                'email_verified_at' => '2026-08-22 16:09:23',
                'created_at'        => '2026-08-22 16:09:23',
                'updated_at'        => '2026-08-22 16:09:23',
            ],
            [
                'id'                => 32,
                'username'          => 'Keyla Zea Fanisa',
                'email'             => 'keylazeafanisa@gmail.com',
                'password'          => '$2y$12$UFLxdjBkHVNJlxuxIqP3mu4NhKTM/YG154EteW87mi7.QbRfOfL1q',
                'role'              => 'siswa',
                'email_verified_at' => '2026-08-22 16:09:23',
                'created_at'        => '2026-08-22 16:09:23',
                'updated_at'        => '2026-08-22 16:09:23',
            ],
            [
                'id'                => 33,
                'username'          => 'Akbar Raiz',
                'email'             => 'akbarraiz@gmail.com',
                'password'          => '$2y$12$OodqridwqQmih6lx3VQ9xu9Gs3Xv7.PaSMtQdE0HkPFtshJdDENUS',
                'role'              => 'siswa',
                'email_verified_at' => '2026-08-22 16:09:24',
                'created_at'        => '2026-08-22 16:09:24',
                'updated_at'        => '2026-08-22 16:09:24',
            ],
            [
                'id'                => 34,
                'username'          => 'Azka Artanabil',
                'email'             => 'azkaartanabil@gmail.com',
                'password'          => '$2y$12$a/9nNAJz.2ERcqZFVrZd5O/Y56kZvah2ovLokVCOq4bnIHbWqm/ki',
                'role'              => 'siswa',
                'email_verified_at' => '2026-08-22 16:09:24',
                'created_at'        => '2026-08-22 16:09:24',
                'updated_at'        => '2026-08-22 16:09:24',
            ],
            [
                'id'                => 35,
                'username'          => 'Nazril Mudzdzafar',
                'email'             => 'nazrilmudzdzafar@gmail.com',
                'password'          => '$2y$12$ZJrPN4hAb2.8NHfsWK6BYu6mHK/XnK46gI21DbiPrJ5zq0Zsz3M/O',
                'role'              => 'siswa',
                'email_verified_at' => '2026-08-22 16:09:24',
                'created_at'        => '2026-08-22 16:09:24',
                'updated_at'        => '2026-08-22 16:09:24',
            ],
            [
                'id'                => 36,
                'username'          => 'Ziris Haidar Alexi',
                'email'             => 'zirishaidaralexi@gmail.com',
                'password'          => '$2y$12$HVugQ4MIkNsURwXJbI4kOe5.Ha0zPzBhBV4ZLjJRm76vO6wwC/suu',
                'role'              => 'siswa',
                'email_verified_at' => '2026-08-22 16:09:25',
                'created_at'        => '2026-08-22 16:09:25',
                'updated_at'        => '2026-08-22 16:09:25',
            ],
            [
                'id'                => 37,
                'username'          => 'Citra Syakira',
                'email'             => 'citrasyakira@gmail.com',
                'password'          => '$2y$12$iR/SVmtXbD3a5LffONHJK.L08VdInBftJRdQ3TC9eLYvBA5K5jC.K',
                'role'              => 'siswa',
                'email_verified_at' => '2026-08-22 16:09:25',
                'created_at'        => '2026-08-22 16:09:25',
                'updated_at'        => '2026-08-22 16:09:25',
            ],
            [
                'id'                => 38,
                'username'          => 'Vezia Almeca Naza',
                'email'             => 'veziaalmecanaza@gmail.com',
                'password'          => '$2y$12$OzHz/DUQ8MmNU7UoPSENFuXWtKhWvrxEUY9IRP99wkUqbGENO3HUe',
                'role'              => 'siswa',
                'email_verified_at' => '2026-08-22 16:09:25',
                'created_at'        => '2026-08-22 16:09:25',
                'updated_at'        => '2026-08-22 16:09:25',
            ],
            [
                'id'                => 39,
                'username'          => 'Febrian Syahputra',
                'email'             => 'febriansyahputra@gmail.com',
                'password'          => '$2y$12$W9oVwsgy5AjILmYmWpMtNuVX9Zvvc2CpY.rst5qH6jBGrBn1O8foK',
                'role'              => 'siswa',
                'email_verified_at' => '2026-08-22 16:09:26',
                'created_at'        => '2026-08-22 16:09:26',
                'updated_at'        => '2026-08-22 16:09:26',
            ],
            [
                'id'                => 40,
                'username'          => 'Muhammad Zain Alfatih',
                'email'             => 'muhammadzainalfatih@gmail.com',
                'password'          => '$2y$12$.aY0iyO3XDCUsQVJ0.pZA.yPUdv3HBIHXxylwEW4/tmBWRVuj7G9C',
                'role'              => 'siswa',
                'email_verified_at' => '2026-08-22 16:09:26',
                'created_at'        => '2026-08-22 16:09:26',
                'updated_at'        => '2026-08-22 16:09:26',
            ],
        ];

        foreach ($users as $user) {
            DB::table('users')->updateOrInsert(['id' => $user['id']], $user);
        }

        // ---------------------------------------------------------------
        // DATA PENDAFTARANS (39 formulir calon siswa)
        // ---------------------------------------------------------------
        $pendaftarans = [
            [
                'id'                    => 1,
                'user_id'               => 2,
                'nama_lengkap'          => 'Atha Rayhaan Shakeil',
                'nik'                   => '1608032601200001',
                'pas_foto_path'         => null,
                'asal_sekolah'          => 'TK ABA Harjowinangun',
                'tempat_lahir'          => 'OKU Timur',
                'tanggal_lahir'         => '2020-01-26',
                'jenis_kelamin'         => 'L',
                'alamat'                => 'Tanjung Raya Belitang',
                'nama_orang_tua'        => '1. Anta Bilhuda 2. Sri Wahyuni',
                'no_hp_wali'            => '0856 0935 7655',
                'status'                => 'lulus',
                'payment_status'        => 'cicilan',
                'amount_paid'           => 100000.00,
                'bukti_pembayaran_path' => null,
                'catatan_pembayaran'    => 'Pembayaran Rp 100.000 disetujui. Cicilan sudah masuk',
                'created_at'            => '2026-08-22 14:23:22',
                'updated_at'            => '2026-08-22 15:24:01',
            ],
            [
                'id'                    => 2,
                'user_id'               => 3,
                'nama_lengkap'          => 'AZZAHRA SALSABILA',
                'nik'                   => '1608034607200001',
                'pas_foto_path'         => 'pas_foto/foto_azzahra_salsabila_qgUrWeqJrmL8E9YFQccl.jpg',
                'asal_sekolah'          => 'PAUD Kasih Ibu Sidomakmur',
                'tempat_lahir'          => 'OKU Timur',
                'tanggal_lahir'         => '2020-07-06',
                'jenis_kelamin'         => 'P',
                'alamat'                => 'Sidomakmur',
                'nama_orang_tua'        => '1. Randi Iwantoro 2. Maya Resti',
                'no_hp_wali'            => '085840234706',
                'status'                => 'lulus',
                'payment_status'        => 'belum_bayar',
                'amount_paid'           => 0.00,
                'bukti_pembayaran_path' => null,
                'catatan_pembayaran'    => null,
                'created_at'            => '2026-08-22 15:41:00',
                'updated_at'            => '2026-08-22 15:46:32',
            ],
            [
                'id'                    => 3,
                'user_id'               => 4,
                'nama_lengkap'          => 'KEYSHA AL-KHANZA',
                'nik'                   => '1608037008190001',
                'pas_foto_path'         => 'pas_foto/foto_keysha_al_khanza_T8wMxPIK7blc7WBQsBgV.jpg',
                'asal_sekolah'          => 'PAUD Kasih Ibu Sidomakmur',
                'tempat_lahir'          => 'OKU Timur',
                'tanggal_lahir'         => '2019-08-30',
                'jenis_kelamin'         => 'P',
                'alamat'                => 'Sidomakmur',
                'nama_orang_tua'        => '1. Riki Hermawan 2. Sagita Putri Lesmana',
                'no_hp_wali'            => '085709147368',
                'status'                => 'lulus',
                'payment_status'        => 'belum_bayar',
                'amount_paid'           => 0.00,
                'bukti_pembayaran_path' => null,
                'catatan_pembayaran'    => null,
                'created_at'            => '2026-08-22 15:41:01',
                'updated_at'            => '2026-08-22 15:46:35',
            ],
            [
                'id'                    => 4,
                'user_id'               => 5,
                'nama_lengkap'          => 'NADHIRA RAHMA FALISHA',
                'nik'                   => '1608036707200001',
                'pas_foto_path'         => 'pas_foto/foto_nadhira_rahma_falisha_oZgghY7hRQjldrFyksb3.jpg',
                'asal_sekolah'          => 'TK ABA Harjowinangun',
                'tempat_lahir'          => 'OKU Timur',
                'tanggal_lahir'         => '2020-07-27',
                'jenis_kelamin'         => 'P',
                'alamat'                => 'Sidogede',
                'nama_orang_tua'        => '1. Sito Kastoyo 2. Siti Kholifatul Motmainah',
                'no_hp_wali'            => '081273833632',
                'status'                => 'lulus',
                'payment_status'        => 'belum_bayar',
                'amount_paid'           => 0.00,
                'bukti_pembayaran_path' => null,
                'catatan_pembayaran'    => null,
                'created_at'            => '2026-08-22 15:41:01',
                'updated_at'            => '2026-08-22 15:46:44',
            ],
            [
                'id'                    => 5,
                'user_id'               => 6,
                'nama_lengkap'          => 'ZAIDAN SYAFIQ ARDIAZ',
                'nik'                   => '1608030208200001',
                'pas_foto_path'         => 'pas_foto/foto_zaidan_syafiq_ardiaz_89ZcV4HVIg1vN8nmeS1E.jpg',
                'asal_sekolah'          => 'TK ABA Harjowinangun',
                'tempat_lahir'          => 'OKU Timur',
                'tanggal_lahir'         => '2020-08-02',
                'jenis_kelamin'         => 'L',
                'alamat'                => 'Sidogede',
                'nama_orang_tua'        => '1. Ardianto, M.Pd 2. Zumroton Nikmah, S.Pd.',
                'no_hp_wali'            => '085839986594',
                'status'                => 'lulus',
                'payment_status'        => 'belum_bayar',
                'amount_paid'           => 0.00,
                'bukti_pembayaran_path' => null,
                'catatan_pembayaran'    => null,
                'created_at'            => '2026-08-22 15:41:02',
                'updated_at'            => '2026-08-22 15:46:48',
            ],
            [
                'id'                    => 6,
                'user_id'               => 7,
                'nama_lengkap'          => 'ARSYA MAULANA ROMADHAN',
                'nik'                   => '1608030105200001',
                'pas_foto_path'         => 'pas_foto/foto_arsya_maulana_romadhan_UX5nIMDcgoFqePzXjAtk.jpg',
                'asal_sekolah'          => 'RA Nurul Huda Sidomakmur',
                'tempat_lahir'          => 'OKU Timur',
                'tanggal_lahir'         => '2020-05-01',
                'jenis_kelamin'         => 'L',
                'alamat'                => 'Sidomakmur',
                'nama_orang_tua'        => '1. Ahmad Tukiyan 2. Nia Widiani',
                'no_hp_wali'            => '082181491159',
                'status'                => 'lulus',
                'payment_status'        => 'belum_bayar',
                'amount_paid'           => 0.00,
                'bukti_pembayaran_path' => null,
                'catatan_pembayaran'    => null,
                'created_at'            => '2026-08-22 15:41:02',
                'updated_at'            => '2026-08-22 15:46:29',
            ],
            [
                'id'                    => 7,
                'user_id'               => 8,
                'nama_lengkap'          => 'SALSA KIRANA ZAHRANI',
                'nik'                   => '1608034506200001',
                'pas_foto_path'         => 'pas_foto/foto_salsa_kirana_zahrani_f05gWN3kPqdzw9TBS5ja.jpg',
                'asal_sekolah'          => 'RA Nurul Huda Sidomakmur',
                'tempat_lahir'          => 'OKU Timur',
                'tanggal_lahir'         => '2020-06-05',
                'jenis_kelamin'         => 'P',
                'alamat'                => 'Sidomakmur',
                'nama_orang_tua'        => '1. Antono 2. Tilawati',
                'no_hp_wali'            => '085373020355',
                'status'                => 'menunggu_verifikasi',
                'payment_status'        => 'belum_bayar',
                'amount_paid'           => 0.00,
                'bukti_pembayaran_path' => null,
                'catatan_pembayaran'    => null,
                'created_at'            => '2026-08-22 16:09:16',
                'updated_at'            => '2026-08-22 16:09:16',
            ],
            [
                'id'                    => 8,
                'user_id'               => 9,
                'nama_lengkap'          => 'HUSNA AYUNINDYA',
                'nik'                   => '1608035110190001',
                'pas_foto_path'         => 'pas_foto/foto_husna_ayunindya_dHHOTgjxB4qBMZhBI4l9.jpg',
                'asal_sekolah'          => 'RA Nurul Huda Sidomakmur',
                'tempat_lahir'          => 'OKU Timur',
                'tanggal_lahir'         => '2019-10-11',
                'jenis_kelamin'         => 'P',
                'alamat'                => 'Sidomakmur',
                'nama_orang_tua'        => '1. Hasyim Muhamad Sobri 2. Siti Maisyaroh',
                'no_hp_wali'            => '085840000008',
                'status'                => 'lulus',
                'payment_status'        => 'belum_bayar',
                'amount_paid'           => 0.00,
                'bukti_pembayaran_path' => null,
                'catatan_pembayaran'    => null,
                'created_at'            => '2026-08-22 16:09:16',
                'updated_at'            => '2026-08-22 16:14:49',
            ],
            [
                'id'                    => 9,
                'user_id'               => 10,
                'nama_lengkap'          => 'KAREL AL SADAD',
                'nik'                   => '1608031911190001',
                'pas_foto_path'         => 'pas_foto/foto_karel_al_sadad_mMlOVUzbYGeRKAPo6fS1.jpg',
                'asal_sekolah'          => 'TK Imam Bonjol Gumawang',
                'tempat_lahir'          => 'OKU Timur',
                'tanggal_lahir'         => '2019-11-19',
                'jenis_kelamin'         => 'L',
                'alamat'                => 'Tegalrejo',
                'nama_orang_tua'        => '1. Ahmad Zainal Arifin 2. Marfiana Lestari',
                'no_hp_wali'            => '081391399054',
                'status'                => 'lulus',
                'payment_status'        => 'belum_bayar',
                'amount_paid'           => 0.00,
                'bukti_pembayaran_path' => null,
                'catatan_pembayaran'    => null,
                'created_at'            => '2026-08-22 16:09:17',
                'updated_at'            => '2026-08-22 16:14:53',
            ],
            [
                'id'                    => 10,
                'user_id'               => 11,
                'nama_lengkap'          => 'AFIFA TITIYA',
                'nik'                   => '1608034609190001',
                'pas_foto_path'         => 'pas_foto/foto_afifa_titiya_nmmbhGycgaZQhIycZh1Y.jpg',
                'asal_sekolah'          => 'KB Al Fatah Sidogede',
                'tempat_lahir'          => 'OKU Timur',
                'tanggal_lahir'         => '2019-09-06',
                'jenis_kelamin'         => 'P',
                'alamat'                => 'Sidogede',
                'nama_orang_tua'        => '1. Tusimin 2. Nora Filiyanti',
                'no_hp_wali'            => '085691675912',
                'status'                => 'lulus',
                'payment_status'        => 'belum_bayar',
                'amount_paid'           => 0.00,
                'bukti_pembayaran_path' => null,
                'catatan_pembayaran'    => null,
                'created_at'            => '2026-08-22 16:09:17',
                'updated_at'            => '2026-08-22 16:13:13',
            ],
            [
                'id'                    => 11,
                'user_id'               => 12,
                'nama_lengkap'          => 'M. SYAILENDRA DIRGA VERNANDO',
                'nik'                   => '1608032403200001',
                'pas_foto_path'         => 'pas_foto/foto_syailendra_dirga_mADaRWmWxioLuiEr6Kk8.jpg',
                'asal_sekolah'          => 'TK ABA Tulus Ayu',
                'tempat_lahir'          => 'OKU Timur',
                'tanggal_lahir'         => '2020-03-24',
                'jenis_kelamin'         => 'L',
                'alamat'                => 'Tulus Ayu',
                'nama_orang_tua'        => '1. Redho Vernando 2. Indah Utami',
                'no_hp_wali'            => '085709570651',
                'status'                => 'lulus',
                'payment_status'        => 'belum_bayar',
                'amount_paid'           => 0.00,
                'bukti_pembayaran_path' => null,
                'catatan_pembayaran'    => null,
                'created_at'            => '2026-08-22 16:09:18',
                'updated_at'            => '2026-08-22 16:15:04',
            ],
            [
                'id'                    => 12,
                'user_id'               => 13,
                'nama_lengkap'          => 'ANGGA WIJAYA',
                'nik'                   => '1608032211190001',
                'pas_foto_path'         => 'pas_foto/foto_angga_wijaya_mAyYK8HoTWxjPbQ0HUiA.jpg',
                'asal_sekolah'          => 'KB Al Fatah Sidogede',
                'tempat_lahir'          => 'OKU Timur',
                'tanggal_lahir'         => '2019-11-22',
                'jenis_kelamin'         => 'L',
                'alamat'                => 'Sidogede',
                'nama_orang_tua'        => '1. Suherman 2. Nurmala Sari',
                'no_hp_wali'            => '085700000012',
                'status'                => 'lulus',
                'payment_status'        => 'belum_bayar',
                'amount_paid'           => 0.00,
                'bukti_pembayaran_path' => null,
                'catatan_pembayaran'    => null,
                'created_at'            => '2026-08-22 16:09:18',
                'updated_at'            => '2026-08-22 16:13:49',
            ],
            [
                'id'                    => 13,
                'user_id'               => 14,
                'nama_lengkap'          => 'AISYAH',
                'nik'                   => '1608034311190001',
                'pas_foto_path'         => 'pas_foto/foto_aisyah_M6wh2SalHUsQoHkEfJnF.jpg',
                'asal_sekolah'          => 'KB Al Fatah Sidogede',
                'tempat_lahir'          => 'OKU Timur',
                'tanggal_lahir'         => '2019-11-03',
                'jenis_kelamin'         => 'P',
                'alamat'                => 'Sidogede',
                'nama_orang_tua'        => '1. Heri Suharyanto 2. Naria Afriandika Parulian',
                'no_hp_wali'            => '085700000013',
                'status'                => 'tidak_lulus',
                'payment_status'        => 'belum_bayar',
                'amount_paid'           => 0.00,
                'bukti_pembayaran_path' => null,
                'catatan_pembayaran'    => null,
                'created_at'            => '2026-08-22 16:09:18',
                'updated_at'            => '2026-08-23 01:48:08',
            ],
            [
                'id'                    => 14,
                'user_id'               => 15,
                'nama_lengkap'          => 'ALIFA AZZALIA',
                'nik'                   => '1608034406200001',
                'pas_foto_path'         => 'pas_foto/foto_alifa_azzalia_Ka09krIxvPO4gzbhrTML.jpg',
                'asal_sekolah'          => 'KB Al Fatah Sidogede',
                'tempat_lahir'          => 'OKU Timur',
                'tanggal_lahir'         => '2020-06-04',
                'jenis_kelamin'         => 'P',
                'alamat'                => 'Sidogede',
                'nama_orang_tua'        => '1. Hendri Purwoko 2. Supiyati',
                'no_hp_wali'            => '085700000014',
                'status'                => 'lulus',
                'payment_status'        => 'belum_bayar',
                'amount_paid'           => 0.00,
                'bukti_pembayaran_path' => null,
                'catatan_pembayaran'    => null,
                'created_at'            => '2026-08-22 16:09:18',
                'updated_at'            => '2026-08-22 16:13:42',
            ],
            [
                'id'                    => 15,
                'user_id'               => 16,
                'nama_lengkap'          => 'BILAL AL RASYID',
                'nik'                   => '1608033105200001',
                'pas_foto_path'         => 'pas_foto/foto_bilal_al_rasyid_BSvut6zVWvxhe9jBMhwj.jpg',
                'asal_sekolah'          => 'KB Al Fatah Sidogede',
                'tempat_lahir'          => 'OKU Timur',
                'tanggal_lahir'         => '2020-05-31',
                'jenis_kelamin'         => 'L',
                'alamat'                => 'Sidogede',
                'nama_orang_tua'        => '1. Sudarsono 2. Muhayati',
                'no_hp_wali'            => '085700000015',
                'status'                => 'tidak_lulus',
                'payment_status'        => 'belum_bayar',
                'amount_paid'           => 0.00,
                'bukti_pembayaran_path' => null,
                'catatan_pembayaran'    => null,
                'created_at'            => '2026-08-22 16:09:19',
                'updated_at'            => '2026-08-22 16:14:30',
            ],
            [
                'id'                    => 16,
                'user_id'               => 17,
                'nama_lengkap'          => 'ASYIFA UMI SABRINA',
                'nik'                   => '1608034512190001',
                'pas_foto_path'         => 'pas_foto/foto_asyifa_umi_sabrina_27xFLjF76LpqLpgG0Gla.jpg',
                'asal_sekolah'          => 'KB Al Fatah Sidogede',
                'tempat_lahir'          => 'OKU Timur',
                'tanggal_lahir'         => '2019-12-05',
                'jenis_kelamin'         => 'P',
                'alamat'                => 'Sidogede',
                'nama_orang_tua'        => '1. Aris Wibowo 2. Feri Indriyani',
                'no_hp_wali'            => '085700000016',
                'status'                => 'lulus',
                'payment_status'        => 'belum_bayar',
                'amount_paid'           => 0.00,
                'bukti_pembayaran_path' => null,
                'catatan_pembayaran'    => null,
                'created_at'            => '2026-08-22 16:09:19',
                'updated_at'            => '2026-08-22 16:14:05',
            ],
            [
                'id'                    => 17,
                'user_id'               => 18,
                'nama_lengkap'          => 'AZWAN RAFASYA',
                'nik'                   => '1608030101200001',
                'pas_foto_path'         => 'pas_foto/foto_azwan_rafasya_n7G14GFJSyzHSabbt2Xi.jpg',
                'asal_sekolah'          => 'KB Al Fatah Sidogede',
                'tempat_lahir'          => 'OKU Timur',
                'tanggal_lahir'         => '2020-01-01',
                'jenis_kelamin'         => 'L',
                'alamat'                => 'Sidogede',
                'nama_orang_tua'        => '1. Ariyandi Okta Wirnata 2. Rina Sunarti',
                'no_hp_wali'            => '085700000017',
                'status'                => 'lulus',
                'payment_status'        => 'menunggu_konfirmasi',
                'amount_paid'           => 100000.00,
                'bukti_pembayaran_path' => 'pembayaran/mpPpnbHwwKsHwD1711Tbb3Rkc6YiGsSzEorC3mOu.png',
                'catatan_pembayaran'    => null,
                'created_at'            => '2026-08-22 16:09:19',
                'updated_at'            => '2026-08-23 01:58:55',
            ],
            [
                'id'                    => 18,
                'user_id'               => 19,
                'nama_lengkap'          => 'ALFANIA LAYLA SYAKIRA RAMADHANI',
                'nik'                   => '1608036704200001',
                'pas_foto_path'         => 'pas_foto/foto_alfania_layla_syakira_VQQQdzQu6DKdVMrtFh4U.jpg',
                'asal_sekolah'          => 'KB Al Fatah Sidogede',
                'tempat_lahir'          => 'OKU Timur',
                'tanggal_lahir'         => '2020-04-27',
                'jenis_kelamin'         => 'P',
                'alamat'                => 'Sidogede',
                'nama_orang_tua'        => '1. Ahmad Sarjono 2. Animawati',
                'no_hp_wali'            => '085700000018',
                'status'                => 'lulus',
                'payment_status'        => 'belum_bayar',
                'amount_paid'           => 0.00,
                'bukti_pembayaran_path' => null,
                'catatan_pembayaran'    => null,
                'created_at'            => '2026-08-22 16:09:20',
                'updated_at'            => '2026-08-22 16:13:38',
            ],
            [
                'id'                    => 19,
                'user_id'               => 20,
                'nama_lengkap'          => 'RIZKI MAULANA SAPUTRA',
                'nik'                   => '1608030811190001',
                'pas_foto_path'         => 'pas_foto/foto_rizki_maulana_saputra_orapcYr5O738YxXdXjr2.jpg',
                'asal_sekolah'          => 'KB Al Fatah Sidogede',
                'tempat_lahir'          => 'OKU Timur',
                'tanggal_lahir'         => '2019-11-08',
                'jenis_kelamin'         => 'L',
                'alamat'                => 'Sidogede',
                'nama_orang_tua'        => '1. Yusuf 2. Anggi Larasati',
                'no_hp_wali'            => '085700000019',
                'status'                => 'lulus',
                'payment_status'        => 'belum_bayar',
                'amount_paid'           => 0.00,
                'bukti_pembayaran_path' => null,
                'catatan_pembayaran'    => null,
                'created_at'            => '2026-08-22 16:09:20',
                'updated_at'            => '2026-08-22 16:15:35',
            ],
            [
                'id'                    => 20,
                'user_id'               => 21,
                'nama_lengkap'          => 'AL KHAISYAN PUTRA PAMUNGKAS',
                'nik'                   => '1608032009190001',
                'pas_foto_path'         => 'pas_foto/foto_al_khaisyan_putra_JHD84lxpwOpp2MK17jwn.jpg',
                'asal_sekolah'          => 'TK Mandiri Bangka',
                'tempat_lahir'          => 'Bangka',
                'tanggal_lahir'         => '2019-09-20',
                'jenis_kelamin'         => 'L',
                'alamat'                => 'Tanjung Raya',
                'nama_orang_tua'        => '1. Yogi 2. Nira',
                'no_hp_wali'            => '085700000020',
                'status'                => 'lulus',
                'payment_status'        => 'belum_bayar',
                'amount_paid'           => 0.00,
                'bukti_pembayaran_path' => null,
                'catatan_pembayaran'    => null,
                'created_at'            => '2026-08-22 16:09:20',
                'updated_at'            => '2026-08-22 16:13:34',
            ],
            [
                'id'                    => 21,
                'user_id'               => 22,
                'nama_lengkap'          => 'KMS. MUHAMMAD ROFIQ AL MAULIDY',
                'nik'                   => '1608031111200001',
                'pas_foto_path'         => 'pas_foto/foto_muhammad_rofiq_pUsK4HW83rSD8K8eMLDl.jpg',
                'asal_sekolah'          => 'TK ABA Bedilan',
                'tempat_lahir'          => 'OKU Timur',
                'tanggal_lahir'         => '2020-11-11',
                'jenis_kelamin'         => 'L',
                'alamat'                => 'Jaya Bakti',
                'nama_orang_tua'        => '1. Kms. M. Andri Juwaidi, MARS 2. Atika Nur Maghfiroh',
                'no_hp_wali'            => '085382006100',
                'status'                => 'lulus',
                'payment_status'        => 'belum_bayar',
                'amount_paid'           => 0.00,
                'bukti_pembayaran_path' => null,
                'catatan_pembayaran'    => null,
                'created_at'            => '2026-08-22 16:09:20',
                'updated_at'            => '2026-08-22 16:15:01',
            ],
            [
                'id'                    => 22,
                'user_id'               => 23,
                'nama_lengkap'          => 'NAD NAZHIF FIKRI',
                'nik'                   => '1608031612160001',
                'pas_foto_path'         => 'pas_foto/foto_nad_nazhif_fikri_OOMymF6vABRI8HeAYbs5.jpg',
                'asal_sekolah'          => 'SD IT Al-Inayah Lb. Harjo (Kls A)',
                'tempat_lahir'          => 'OKU Timur',
                'tanggal_lahir'         => '2016-12-16',
                'jenis_kelamin'         => 'L',
                'alamat'                => 'Lubuk Harjo',
                'nama_orang_tua'        => '1. Jazim Ryfai 2. Jumara Santi',
                'no_hp_wali'            => '081273833076',
                'status'                => 'lulus',
                'payment_status'        => 'belum_bayar',
                'amount_paid'           => 0.00,
                'bukti_pembayaran_path' => null,
                'catatan_pembayaran'    => null,
                'created_at'            => '2026-08-22 16:09:21',
                'updated_at'            => '2026-08-22 16:15:19',
            ],
            [
                'id'                    => 23,
                'user_id'               => 24,
                'nama_lengkap'          => 'ERINA RAYYA ASSYAUQIE',
                'nik'                   => '1608035405200001',
                'pas_foto_path'         => 'pas_foto/foto_erina_rayya_odgA86dHH4HLLJX3Sof5.jpg',
                'asal_sekolah'          => 'TK ABA Harjowinangun',
                'tempat_lahir'          => 'OKU Timur',
                'tanggal_lahir'         => '2020-05-14',
                'jenis_kelamin'         => 'P',
                'alamat'                => 'Sidogede',
                'nama_orang_tua'        => '1. Tri Wahyudi 2. Lidya Sari',
                'no_hp_wali'            => '085832411002',
                'status'                => 'lulus',
                'payment_status'        => 'belum_bayar',
                'amount_paid'           => 0.00,
                'bukti_pembayaran_path' => null,
                'catatan_pembayaran'    => null,
                'created_at'            => '2026-08-22 16:09:21',
                'updated_at'            => '2026-08-22 16:14:38',
            ],
            [
                'id'                    => 24,
                'user_id'               => 25,
                'nama_lengkap'          => 'HAFIZ NUR RAHMAN',
                'nik'                   => '1608030205200001',
                'pas_foto_path'         => 'pas_foto/foto_hafiz_nur_rahman_GlWZCIC93TNHMseOlu11.jpg',
                'asal_sekolah'          => '-',
                'tempat_lahir'          => 'OKU Timur',
                'tanggal_lahir'         => '2020-05-02',
                'jenis_kelamin'         => 'L',
                'alamat'                => 'Sidogede',
                'nama_orang_tua'        => '1. Eliyanto 2. Mei Rusmawati',
                'no_hp_wali'            => '085793825789',
                'status'                => 'lulus',
                'payment_status'        => 'belum_bayar',
                'amount_paid'           => 0.00,
                'bukti_pembayaran_path' => null,
                'catatan_pembayaran'    => null,
                'created_at'            => '2026-08-22 16:09:21',
                'updated_at'            => '2026-08-22 16:14:45',
            ],
            [
                'id'                    => 25,
                'user_id'               => 26,
                'nama_lengkap'          => 'SAFFANA NASHA FAWZIA',
                'nik'                   => '1608036602200001',
                'pas_foto_path'         => 'pas_foto/foto_saffana_nasha_MJ1uCiUfRzEaijsU36d6.jpg',
                'asal_sekolah'          => 'TK Imam Bonjol Gumawang',
                'tempat_lahir'          => 'OKU Timur',
                'tanggal_lahir'         => '2020-02-26',
                'jenis_kelamin'         => 'P',
                'alamat'                => 'Sidogede',
                'nama_orang_tua'        => '1. Imam Ma\'ruf 2. Nur Aliyah Sya\'ban',
                'no_hp_wali'            => '085244613234',
                'status'                => 'menunggu_verifikasi',
                'payment_status'        => 'belum_bayar',
                'amount_paid'           => 0.00,
                'bukti_pembayaran_path' => null,
                'catatan_pembayaran'    => null,
                'created_at'            => '2026-08-22 16:09:22',
                'updated_at'            => '2026-08-22 16:09:22',
            ],
            [
                'id'                    => 26,
                'user_id'               => 27,
                'nama_lengkap'          => 'NOVAL DEVAN AT TAIMIFAH',
                'nik'                   => '1608031410190001',
                'pas_foto_path'         => 'pas_foto/foto_noval_devan_3cQymWNEqeBshl3SapGC.jpg',
                'asal_sekolah'          => 'TK ABA Harjowinangun',
                'tempat_lahir'          => 'OKU Timur',
                'tanggal_lahir'         => '2019-10-14',
                'jenis_kelamin'         => 'L',
                'alamat'                => 'Sidogede',
                'nama_orang_tua'        => '1. Ahmad Abdullah Attaimifah 2. Ratna Juwita',
                'no_hp_wali'            => '085789557448',
                'status'                => 'lulus',
                'payment_status'        => 'belum_bayar',
                'amount_paid'           => 0.00,
                'bukti_pembayaran_path' => null,
                'catatan_pembayaran'    => null,
                'created_at'            => '2026-08-22 16:09:22',
                'updated_at'            => '2026-08-22 16:15:32',
            ],
            [
                'id'                    => 27,
                'user_id'               => 28,
                'nama_lengkap'          => 'ALYA DINDA KAMALA',
                'nik'                   => '1608034502200001',
                'pas_foto_path'         => 'pas_foto/foto_alya_dinda_kamala_jG7hzBffIwvxcKmcVo58.jpg',
                'asal_sekolah'          => 'TK Al Hayati',
                'tempat_lahir'          => 'OKU Timur',
                'tanggal_lahir'         => '2020-02-05',
                'jenis_kelamin'         => 'P',
                'alamat'                => 'Harjowinangun',
                'nama_orang_tua'        => '1. Sugiantoro 2. Leniawati',
                'no_hp_wali'            => '085700000027',
                'status'                => 'lulus',
                'payment_status'        => 'belum_bayar',
                'amount_paid'           => 0.00,
                'bukti_pembayaran_path' => null,
                'catatan_pembayaran'    => null,
                'created_at'            => '2026-08-22 16:09:22',
                'updated_at'            => '2026-08-22 16:13:45',
            ],
            [
                'id'                    => 28,
                'user_id'               => 29,
                'nama_lengkap'          => 'MUHAIMIN AHMAD',
                'nik'                   => '1608033011190001',
                'pas_foto_path'         => 'pas_foto/foto_muhaimin_ahmad_vo6yVuRajrQK78k9Tx6E.jpg',
                'asal_sekolah'          => '-',
                'tempat_lahir'          => 'Palembang',
                'tanggal_lahir'         => '2019-11-30',
                'jenis_kelamin'         => 'L',
                'alamat'                => 'Palembang - Gumawang',
                'nama_orang_tua'        => '1. Sakban 2. Seri Wahyuningsih',
                'no_hp_wali'            => '085700000028',
                'status'                => 'lulus',
                'payment_status'        => 'belum_bayar',
                'amount_paid'           => 0.00,
                'bukti_pembayaran_path' => null,
                'catatan_pembayaran'    => null,
                'created_at'            => '2026-08-22 16:09:22',
                'updated_at'            => '2026-08-22 16:15:08',
            ],
            [
                'id'                    => 29,
                'user_id'               => 30,
                'nama_lengkap'          => 'NARENDRA RAYYAN ATHA RAZKA',
                'nik'                   => '1608031312190001',
                'pas_foto_path'         => 'pas_foto/foto_narendra_rayyan_38cqky5dNxoumHb9Oteu.jpg',
                'asal_sekolah'          => 'TK An Nur Sidogede',
                'tempat_lahir'          => 'OKU Timur',
                'tanggal_lahir'         => '2019-12-13',
                'jenis_kelamin'         => 'L',
                'alamat'                => 'Sidogede',
                'nama_orang_tua'        => '1. Muti M. Barok',
                'no_hp_wali'            => '085700000029',
                'status'                => 'lulus',
                'payment_status'        => 'belum_bayar',
                'amount_paid'           => 0.00,
                'bukti_pembayaran_path' => null,
                'catatan_pembayaran'    => null,
                'created_at'            => '2026-08-22 16:09:23',
                'updated_at'            => '2026-08-22 16:15:23',
            ],
            [
                'id'                    => 30,
                'user_id'               => 31,
                'nama_lengkap'          => 'MUHAMMAD HAIDAR EL FAYYADH',
                'nik'                   => '1608032002200001',
                'pas_foto_path'         => 'pas_foto/foto_haidar_el_fayyadh_TG4yqA1dTJxV20Ow62mm.jpg',
                'asal_sekolah'          => 'TK IT An Nur Sidogede',
                'tempat_lahir'          => 'OKU Timur',
                'tanggal_lahir'         => '2020-02-20',
                'jenis_kelamin'         => 'L',
                'alamat'                => 'Sidogede',
                'nama_orang_tua'        => '1. Sakti Aji Wijaya 2. Hesti Setiyani',
                'no_hp_wali'            => '085700000030',
                'status'                => 'lulus',
                'payment_status'        => 'belum_bayar',
                'amount_paid'           => 0.00,
                'bukti_pembayaran_path' => null,
                'catatan_pembayaran'    => null,
                'created_at'            => '2026-08-22 16:09:23',
                'updated_at'            => '2026-08-22 16:15:11',
            ],
            [
                'id'                    => 31,
                'user_id'               => 32,
                'nama_lengkap'          => 'KEYLA ZEA FANISA',
                'nik'                   => '1608037004200001',
                'pas_foto_path'         => 'pas_foto/foto_keyla_zea_fanisa_6BIEq3ckJfMlLXMY0m1O.jpg',
                'asal_sekolah'          => 'TK IT An Nur Sidogede',
                'tempat_lahir'          => 'OKU Timur',
                'tanggal_lahir'         => '2020-04-30',
                'jenis_kelamin'         => 'P',
                'alamat'                => 'Sidogede',
                'nama_orang_tua'        => '1. Heru Marjono 2. Anisa Lutfiandari',
                'no_hp_wali'            => '085700000031',
                'status'                => 'lulus',
                'payment_status'        => 'belum_bayar',
                'amount_paid'           => 0.00,
                'bukti_pembayaran_path' => null,
                'catatan_pembayaran'    => null,
                'created_at'            => '2026-08-22 16:09:23',
                'updated_at'            => '2026-08-22 16:14:57',
            ],
            [
                'id'                    => 32,
                'user_id'               => 33,
                'nama_lengkap'          => 'AKBAR RAIZ',
                'nik'                   => '1608032504200001',
                'pas_foto_path'         => 'pas_foto/foto_akbar_raiz_2LFdlPPpp3fJIri615Di.jpg',
                'asal_sekolah'          => 'TK IT An Nur Sidogede',
                'tempat_lahir'          => 'OKU Timur',
                'tanggal_lahir'         => '2020-04-25',
                'jenis_kelamin'         => 'L',
                'alamat'                => 'Sidogede',
                'nama_orang_tua'        => '1. Hisam Ashari 2. Ni\'mah Novita',
                'no_hp_wali'            => '08131800299',
                'status'                => 'menunggu_verifikasi',
                'payment_status'        => 'belum_bayar',
                'amount_paid'           => 0.00,
                'bukti_pembayaran_path' => null,
                'catatan_pembayaran'    => null,
                'created_at'            => '2026-08-22 16:09:24',
                'updated_at'            => '2026-08-23 01:48:17',
            ],
            [
                'id'                    => 33,
                'user_id'               => 34,
                'nama_lengkap'          => 'AZKA ARTANABIL',
                'nik'                   => '1608031403200001',
                'pas_foto_path'         => 'pas_foto/foto_azka_artanabil_KCEzmVUzGf7iHMHwL2S5.jpg',
                'asal_sekolah'          => 'TK Imam Bonjol',
                'tempat_lahir'          => 'OKU Timur',
                'tanggal_lahir'         => '2020-03-14',
                'jenis_kelamin'         => 'L',
                'alamat'                => 'Sidogede',
                'nama_orang_tua'        => '1. Juli Susianto 2. Erwiyanti',
                'no_hp_wali'            => '085700000033',
                'status'                => 'lulus',
                'payment_status'        => 'belum_bayar',
                'amount_paid'           => 0.00,
                'bukti_pembayaran_path' => null,
                'catatan_pembayaran'    => null,
                'created_at'            => '2026-08-22 16:09:24',
                'updated_at'            => '2026-08-22 16:14:09',
            ],
            [
                'id'                    => 34,
                'user_id'               => 35,
                'nama_lengkap'          => 'NAZRIL MUDZDZAFAR',
                'nik'                   => '1608032206200001',
                'pas_foto_path'         => 'pas_foto/foto_nazril_mudzdzafar_If0ktiZF1hy9t3FJqerb.jpg',
                'asal_sekolah'          => '-',
                'tempat_lahir'          => 'OKU Timur',
                'tanggal_lahir'         => '2020-06-22',
                'jenis_kelamin'         => 'L',
                'alamat'                => 'Bedilan',
                'nama_orang_tua'        => '1. Wagiman 2. Erriya',
                'no_hp_wali'            => '085700000034',
                'status'                => 'lulus',
                'payment_status'        => 'belum_bayar',
                'amount_paid'           => 0.00,
                'bukti_pembayaran_path' => null,
                'catatan_pembayaran'    => null,
                'created_at'            => '2026-08-22 16:09:24',
                'updated_at'            => '2026-08-22 16:15:27',
            ],
            [
                'id'                    => 35,
                'user_id'               => 36,
                'nama_lengkap'          => 'ZIRIS HAIDAR ALEXI',
                'nik'                   => '1608030309200001',
                'pas_foto_path'         => 'pas_foto/foto_ziris_haidar_alexi_qcJLi1xuOiGqjvOE5tR9.jpg',
                'asal_sekolah'          => 'RA Karang Endah',
                'tempat_lahir'          => 'OKU Timur',
                'tanggal_lahir'         => '2020-09-03',
                'jenis_kelamin'         => 'L',
                'alamat'                => 'Karang Endah',
                'nama_orang_tua'        => '1. Hardimansyah 2. Jumirah',
                'no_hp_wali'            => '085700000035',
                'status'                => 'menunggu_verifikasi',
                'payment_status'        => 'belum_bayar',
                'amount_paid'           => 0.00,
                'bukti_pembayaran_path' => null,
                'catatan_pembayaran'    => null,
                'created_at'            => '2026-08-22 16:09:25',
                'updated_at'            => '2026-08-22 16:09:25',
            ],
            [
                'id'                    => 36,
                'user_id'               => 37,
                'nama_lengkap'          => 'CITRA SYAKIRA',
                'nik'                   => '1608034102200001',
                'pas_foto_path'         => 'pas_foto/foto_citra_syakira_9uWPWK55qBR17XYW1T7F.jpg',
                'asal_sekolah'          => 'TK ABA Harjowinangun',
                'tempat_lahir'          => 'OKU Timur',
                'tanggal_lahir'         => '2020-02-01',
                'jenis_kelamin'         => 'P',
                'alamat'                => 'Sidogede',
                'nama_orang_tua'        => '1. Habibi 2. Sri Lestari',
                'no_hp_wali'            => '085700000036',
                'status'                => 'lulus',
                'payment_status'        => 'belum_bayar',
                'amount_paid'           => 0.00,
                'bukti_pembayaran_path' => null,
                'catatan_pembayaran'    => null,
                'created_at'            => '2026-08-22 16:09:25',
                'updated_at'            => '2026-08-22 16:14:34',
            ],
            [
                'id'                    => 37,
                'user_id'               => 38,
                'nama_lengkap'          => 'VEZIA ALMECA NAZA',
                'nik'                   => '1608034311190001',
                'pas_foto_path'         => 'pas_foto/foto_vezia_almeca_naza_20KlEx5C8rKI2aElhHuH.jpg',
                'asal_sekolah'          => 'SDN Bedilan (Kls 2)',
                'tempat_lahir'          => 'OKU Timur',
                'tanggal_lahir'         => '2019-11-03',
                'jenis_kelamin'         => 'P',
                'alamat'                => 'Bedilan',
                'nama_orang_tua'        => '1. Hasan Zaenal Abidin 2. Istiana',
                'no_hp_wali'            => '085700000037',
                'status'                => 'menunggu_verifikasi',
                'payment_status'        => 'belum_bayar',
                'amount_paid'           => 0.00,
                'bukti_pembayaran_path' => null,
                'catatan_pembayaran'    => null,
                'created_at'            => '2026-08-22 16:09:25',
                'updated_at'            => '2026-08-22 16:09:25',
            ],
            [
                'id'                    => 38,
                'user_id'               => 39,
                'nama_lengkap'          => 'FEBRIAN SYAHPUTRA',
                'nik'                   => '1608031402190001',
                'pas_foto_path'         => 'pas_foto/foto_febrian_syahputra_TuZC51WRShQ1BBrbQoFS.jpg',
                'asal_sekolah'          => 'SDN Jakarta Pusat (Kls 3)',
                'tempat_lahir'          => 'Jakarta',
                'tanggal_lahir'         => '2019-02-14',
                'jenis_kelamin'         => 'L',
                'alamat'                => '-',
                'nama_orang_tua'        => '1. Irpan Maulana 2. Nadhotul Umamah',
                'no_hp_wali'            => '085700000038',
                'status'                => 'lulus',
                'payment_status'        => 'belum_bayar',
                'amount_paid'           => 0.00,
                'bukti_pembayaran_path' => null,
                'catatan_pembayaran'    => null,
                'created_at'            => '2026-08-22 16:09:26',
                'updated_at'            => '2026-08-22 16:14:41',
            ],
            [
                'id'                    => 39,
                'user_id'               => 40,
                'nama_lengkap'          => 'MUHAMMAD ZAIN ALFATIH',
                'nik'                   => '1608032604160001',
                'pas_foto_path'         => 'pas_foto/foto_muhammad_zain_alfatih_VH22VJZtFjKUXIVF9NHN.jpg',
                'asal_sekolah'          => '(Kls 4)',
                'tempat_lahir'          => 'OKU Timur',
                'tanggal_lahir'         => '2016-04-26',
                'jenis_kelamin'         => 'L',
                'alamat'                => 'Sidogede',
                'nama_orang_tua'        => '1. Tauhidin 2. Siti Masuroh',
                'no_hp_wali'            => '085700000039',
                'status'                => 'lulus',
                'payment_status'        => 'belum_bayar',
                'amount_paid'           => 0.00,
                'bukti_pembayaran_path' => null,
                'catatan_pembayaran'    => null,
                'created_at'            => '2026-08-22 16:09:26',
                'updated_at'            => '2026-08-22 16:15:14',
            ],
        ];

        foreach ($pendaftarans as $pendaftaran) {
            DB::table('pendaftarans')->updateOrInsert(['id' => $pendaftaran['id']], $pendaftaran);
        }

        // Aktifkan kembali foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $this->command->info('Berhasil melakukan seed 39 data calon siswa & formulir pendaftaran!');
    }
}
